name: Build GPMC on all platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up CMake
      uses: lukka/get-cmake@v3.29.2

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Set binary path by OS
      id: setpath
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          echo "bin_path=build/Release/GPMC.exe" >> "$GITHUB_OUTPUT"
        else
          echo "bin_path=build/GPMC" >> "$GITHUB_OUTPUT"
        fi

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: gpmc-${{ runner.os }}-${{ runner.arch }}
        path: ${{ steps.setpath.outputs.bin_path }}
